### ISSUE TITLE
Login isn't working

### ISSUE THREAD

**Issue by oynozan** [FTCHD/frametrain#46]
I've mentioned the same problem in my pull request, and also as a Warpcast post.

After approving login from Warpcast, sometimes nothing happens, and sometimes it gets stuck at this screen:
![image](https://github.com/FTCHD/frametrain/assets/47722606/ac38ac52-fc65-436f-96b5-e7ecae09809a)

There's no console log. It wants me to log in after I refresh the page. Also cookies are not set even after this screen.

Therefore I can't post Warpcast examples of my templates. This is the application that I try to login: [frametrain-beryl.vercel.app](https://frametrain-beryl.vercel.app/)

Please help, so I can add Warpcast examples of my templates to my pull requests.

**Comment by FTCHD** [comment]
This is usually an issue with your environment configuration. AuthJS in combination with Farcaster Auth is very fickle, and if anything in your `.env` is not set properly it's not going to work. 

If you are sure that everything is set correctly, provide a way to reproduce this issue. Otherwise, I suggest updating your browser or using another one (Edge, Arc, Safari, basically anything that's not your current browser).

**Comment by oynozan** [comment]
I don't think the problem is related to AuthJS. Because I'm actually able to see my profile picture and username after I log in. It just disappears after I refresh the page, and cookies are not generated. My `.env` is set properly. I know this because I was able to log in on `localhost`. Same problem happened with `ngrok` but it got fixed by itself. Now I face with same problem with my Vercel app. I think there's an inconsistency.

You can clone [this](https://github.com/oynozan/frametrain/tree/vercel) repo and try it.
